FROM resin/%%BALENA_MACHINE_NAME%%-alpine-python:3.6-slim

# Defines our working directory in container
RUN mkdir -p /usr/src/app/
WORKDIR /usr/src/app

# This will copy all files in our root to the working directory in the container
COPY ./app ./

# Install Python dependencies
RUN pip install -r requirements.txt

# Start
CMD ["python", "/usr/src/app/application.py"]