FROM resin/%%BALENA_MACHINE_NAME%%-alpine-python:3.6-slim

# Defines our working directory in container
RUN mkdir -p /usr/src/app/
# Copy requirements.txt (speeds up Docker builds)
COPY app/requirements.txt /usr/src/app/requirements.txt
WORKDIR /usr/src/app

# Install Python dependencies
RUN apk add --no-cache make gcc g++ gfortran && \
  pip install numpy && \
  pip install -r requirements.txt

# Copy over the app
COPY ./app ./

# Start
CMD ["python", "/usr/src/app/application.py"]